import '../../styles/index.scss'
import Header from '@/components/Header/Header'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className='body-sass'>
        <Header />
        {children}
      </body>
    </html>
  )
}
